run:
  modules-download-mode: readonly

linters-settings:
  gosec:
    includes:
      - G101
      - G102
      - G103
      - G104
      - G106
      - G108
      - G109
      - G111
      - G113
      - G201
      - G202
      - G203
      - G303
      - G307
      - G403
      - G502
      - G503
      - G504
      - G601
  revive:
    min-confidence: 0
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - Print
          - Printf
          - Println
          - Debug
          - Debugf
          - Info
          - Infof
          - Warn
          - Warnf
          - Error
          - Errorf
  gocritic:
    enabled-checks:
      - commentFormatting
  nolintlint:
    allow-leading-space: false # require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: true # require nolint directives to be specific about which linter is being skipped
  staticcheck:
    go: "1.20"
    checks: [all,-ST1000,-ST1001,-ST1003,-ST1005,-SA1019,-SA4001,-ST1016]

linters:
  disable-all: true
  enable:
    - asciicheck
    - exportloopref
    - gocritic
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - nolintlint
    - rowserrcheck
    - staticcheck
    - wrapcheck
