apiVersion: v1
data:
  configs.yaml: |
    name: ACS audit log
    generic:
      endpoint: http://webhook.stackrox.svc.cluster.local:8080/hook/acs-audit-log
      skipTLSVerify: true
      auditLoggingEnabled: true
kind: ConfigMap
metadata:
  name: declarative-configurations
  namespace: stackrox
