apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webhook
  name: webhook
  namespace: stackrox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  strategy: {}
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - image: some-image
        command:
          - serve
        name: some-image
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhook
  name: webhook
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: webhook
  type: ClusterIP
